---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tqksxakd/public_html
    - set -euo pipefail
    - /bin/mkdir -p "$DEPLOYPATH"

    - /usr/bin/rsync -a --delete "aframe/" "$DEPLOYPATH/aframe/"
    - /usr/bin/rsync -a --delete "doors/"  "$DEPLOYPATH/doors/"
    - /usr/bin/rsync -a --delete "media/"  "$DEPLOYPATH/media/"
    - /usr/bin/rsync -a --delete "js/"     "$DEPLOYPATH/js/"