---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tqksxakd/public_html/site
    - set -euo pipefail
    - /bin/mkdir -p "$DEPLOYPATH"

    - /usr/bin/rsync -a --delete \
        --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
        --exclude ".git/" \
        --exclude ".cpanel.yml" \
        --exclude ".gitignore" \
        --exclude ".DS_Store" \
        --exclude "node_modules/" \
        --exclude "*.mp4" --exclude "*.mov" --exclude "*.mkv" \
        ./ "$DEPLOYPATH/"