---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tqksxakd/public_html/site
    - set -euo pipefail
    - /bin/mkdir -p "$DEPLOYPATH"

    # delete everything EXCEPT media/
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 ! -name "media" -exec /bin/rm -rf {} +

    # deploy tracked files only
    - /usr/bin/git archive --format=tar HEAD | /bin/tar -x -C "$DEPLOYPATH"

    # web-safe perms (do NOT chmod media if you want to keep existing perms)
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 ! -name "media" -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 ! -name "media" -type f -exec /bin/chmod 644 {} \;