---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tqksxakd/public_html/site
    - set -euo pipefail
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "$DEPLOYPATH"/*

    # deploy tracked files only (no .git, no FETCH_HEAD/config/hooks, no random junk)
    - /usr/bin/git archive --format=tar HEAD | /bin/tar -x -C "$DEPLOYPATH"

    # web-safe perms
    - /bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;