---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tqksxakd/public_html
    - set -euo pipefail
    - /bin/mkdir -p "$DEPLOYPATH"

    - /usr/bin/rsync -a --delete \
        --exclude ".git/" \
        --exclude ".cpanel.yml" \
        --exclude ".gitignore" \
        ./ "$DEPLOYPATH/"